site_name: Documentacion

nav:
  - ğŸ  Home: index.md
  - â–¶ï¸ Getting Started: getting_started.md
  - ğŸ³ Docker: docker.md
  - âš™ï¸ Configuration: configurations.md
  - ğŸŒ Endpoints: endpoints.md
  - ğŸ’¾ Database: database.md
  - ğŸ› ï¸ Deployment: deployment.md
  - ğŸ‘¤ About: about.md

plugins:
  - search
  - tags:
      tags_name_variable: tags

theme:
  name: material
  palette:
    accent: gray
    primary: blue
  font:
    text: Roboto
  language: es
  logo: /assets/logo.png
  favicon: /images/logo.png
  features:
    - navigation.path
    - search.suggest

extra:
  font_awesome:
    use_cdn: true
